Feature/accessibility testing (#3)
CI : Run a django test server and run pa11y on several urls to automatically check accessibility.

diff --git a/.github/workflows/pod.yml b/.github/workflows/pod.yml
--- a/.github/workflows/pod.yml
+++ b/.github/workflows/pod.yml
@@ -1,3 +1,4 @@
+---
 name: Django Pod CI
 
 on:
@@ -12,7 +13,7 @@ jobs:
     strategy:
       max-parallel: 4
       matrix:
-        python-version: [3.7, 3.8, 3.9] # , 3.10.6
+        python-version: [3.7, 3.8, 3.9]  # , 3.10.6
 
     steps:
       - uses: actions/checkout@v3
@@ -70,3 +71,53 @@ jobs:
         run: |
           coverage run --source='.' manage.py test -v 3 --settings=pod.main.test_settings
           coveralls  --service=github
+
+      ## Start Accessibility tests with pa11y ##
+
+      - name: Install pa11y-ci dependencies.
+        if: matrix.python-version == 3.9
+        run: |
+          npm install -g Badatos/pa11y-ci
+
+      - name: Run Django test server
+        if: matrix.python-version == 3.9
+        env:
+          PYTHONUNBUFFERED: 1
+        run: |
+          python manage.py loaddata pod/video/fixtures/initial_data.json --settings=pod.main.test_settings
+          python manage.py loaddata pod/main/fixtures/initial_data.json --settings=pod.main.test_settings
+          python manage.py runserver localhost:8080 --insecure --settings=pod.main.test_settings &
+          sleep 5
+
+      - name: Run pa11y-ci.
+        if: matrix.python-version == 3.9
+        # tee reads `stdin` and writes it to both `stdout` and a file
+        run: |
+          pa11y-ci 2>&1 | tee pa11y_output.txt
+
+      - name: Read pa11y_output file.
+        id: pa11y_output
+        if: matrix.python-version == 3.9
+        uses: juliangruber/read-file-action@v1
+        with:
+          path: ./pa11y_output.txt
+
+      - name: Comment on pull request.
+        if: matrix.python-version == 3.9
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          message: '<details><summary>Pa11y testing results</summary>
+
+
+```
+
+${{ steps.pa11y_output.outputs.content }}```
+
+
+</details>'
+      - name: Check for pa11y failures.
+        if: contains(steps.pa11y_output.outputs.content, 'Errors in http://')
+        run: |
+          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
+          exit 1
